// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faqnxvmqwzymhbwlpwpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhcW54dm1xd3p5bWhid2xwd3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjI5NjgsImV4cCI6MjA1OTA5ODk2OH0.--IbAlFNP-tas79En0zWfd4py07MOfbp_UiE7rxK2HY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);